### PR TITLE
added cloud name

### PR DESCRIPTION
**Pull request by asad-rafter**

### CODE REVIEW

**Comment by cld-sec** [comment]
### 🎉 Snyk hasn't found any issues so far.

✅ **security/snyk** check is completed. **No issues were found**. [(View Details)](https://app.snyk.io/org/cloudinaryltd/pr-checks/ab7e83b8-9aa2-4e52-9424-470a986a81fc?refs=9d50f19d79d244cec487eaa2975fa9b57dbd99de&source=prChecksComment)

✅ **license/snyk** check is completed. **No issues were found**. [(View Details)](https://app.snyk.io/org/cloudinaryltd/pr-checks/ab7e83b8-9aa2-4e52-9424-470a986a81fc/license?refs=9d50f19d79d244cec487eaa2975fa9b57dbd99de&source=prChecksComment)

**Review by yuval-cloudinary — CHANGES_REQUESTED** [review]
We already pass the cloudName via ".cloudinary-data-container" (reference below), do we need a new mechanism? If yes, then can we stick to the new mechanism and deprecate the old mechanism?
Please remember we need the CNAME as well


https://github.com/cloudinary/cloudinary_sfcc_pwa-kit/blob/037edeb42d91eb60c8dbea768eb021a3a3543cc4/Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-content-asset/index.jsx#L9

**Comment by asad-rafter** [comment]
> We already pass the cloudName via ".cloudinary-data-container" (reference below), do we need a new mechanism? If yes, then can we stick to the new mechanism and deprecate the old mechanism? Please remember we need the CNAME as well
> 
> https://github.com/cloudinary/cloudinary_sfcc_pwa-kit/blob/037edeb42d91eb60c8dbea768eb021a3a3543cc4/Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-content-asset/index.jsx#L9

The previous implementation only works if we have a content asset or a slot that has data related to the content like HTML. For the new implementation, we need the cloud name everywhere with the existing data.

**Comment by yuval-cloudinary** [comment]
> > We already pass the cloudName via ".cloudinary-data-container" (reference below), do we need a new mechanism? If yes, then can we stick to the new mechanism and deprecate the old mechanism? Please remember we need the CNAME as well
> > https://github.com/cloudinary/cloudinary_sfcc_pwa-kit/blob/037edeb42d91eb60c8dbea768eb021a3a3543cc4/Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-content-asset/index.jsx#L9
> 
> The previous implementation only works if we have a content asset or a slot that has data related to the content like HTML. For the new implementation, we need the cloud name everywhere with the existing data.

In that case, we don't need the old mechanism and can remove it to avoid confusion

**Comment by asad-rafter** [comment]
> > > We already pass the cloudName via ".cloudinary-data-container" (reference below), do we need a new mechanism? If yes, then can we stick to the new mechanism and deprecate the old mechanism? Please remember we need the CNAME as well
> > > https://github.com/cloudinary/cloudinary_sfcc_pwa-kit/blob/037edeb42d91eb60c8dbea768eb021a3a3543cc4/Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-content-asset/index.jsx#L9
> > 
> > 
> > The previous implementation only works if we have a content asset or a slot that has data related to the content like HTML. For the new implementation, we need the cloud name everywhere with the existing data.
> 
> In that case, we don't need the old mechanism and can remove it to avoid confusion

The HTML that has class '.cloudinary-data-container' is coming from the core cartridge as complete HTML, the same template is being used in the core cartridge, and we cannot change that it will have impact on core cartridge as well

**Comment by yuval-cloudinary** [comment]
This is not desired (neither efficient) to pass the global config (cloud_name, cname) on the item level.
Please pass it wither as a DOM object or global JS constant

**Comment by asad-rafter** [comment]
> This is not desired (neither efficient) to pass the global config (cloud_name, cname) on the item level. Please pass it wither as a DOM object or global JS constant

we can move it to product object rather than item

**Comment by asad-rafter** [comment]
> > This is not desired (neither efficient) to pass the global config (cloud_name, cname) on the item level. Please pass it wither as a DOM object or global JS constant
> 
> we can move it to product object rather than item

It doesn't allow to set custom property to product object

**Comment by yuval-cloudinary** [comment]
What about a DOM container (HTML) or a global JS const?

**Comment by asad-rafter** [comment]
> What about a DOM container (HTML) or a global JS const?

In that case it would be hard coded in PWA code base, when there is need to change cloud name we would have to deploy the code again, for now its dynamic coming from custom preferences

**Comment by yuval-cloudinary** [comment]
> > What about a DOM container (HTML) or a global JS const?
> 
> In that case it would be hard coded in PWA code base, when there is need to change cloud name we would have to deploy the code again, for now its dynamic coming from custom preferences

You mentioned that "class '.cloudinary-data-container' is coming from the core cartridge as complete HTML" - can't we do something similar?

**Comment by asad-rafter** [comment]
> > > What about a DOM container (HTML) or a global JS const?
> > 
> > 
> > In that case it would be hard coded in PWA code base, when there is need to change cloud name we would have to deploy the code again, for now its dynamic coming from custom preferences
> 
> You mentioned that "class '.cloudinary-data-container' is coming from the core cartridge as complete HTML" - can't we do something similar?

It will create a separate endpoint that calls the backend and gets the cloud name from preferences, that endpoint will call from the footer or header. Are you aligned with that?

**Comment by yuval-cloudinary** [comment]
> > > > What about a DOM container (HTML) or a global JS const?
> > > 
> > > 
> > > In that case it would be hard coded in PWA code base, when there is need to change cloud name we would have to deploy the code again, for now its dynamic coming from custom preferences
> > 
> > 
> > You mentioned that "class '.cloudinary-data-container' is coming from the core cartridge as complete HTML" - can't we do something similar?
> 
> It will create a separate endpoint that calls the backend and gets the cloud name from preferences, that endpoint will call from the footer or header. Are you aligned with that?

Right now we have an invisible div of class "cloudinary-data-container" in ISML files, which seems to be passed as-is to the PWA and can include both cloud_name and CNAME

**Comment by asad-rafter** [comment]
> > > > > What about a DOM container (HTML) or a global JS const?
> > > > 
> > > > 
> > > > In that case it would be hard coded in PWA code base, when there is need to change cloud name we would have to deploy the code again, for now its dynamic coming from custom preferences
> > > 
> > > 
> > > You mentioned that "class '.cloudinary-data-container' is coming from the core cartridge as complete HTML" - can't we do something similar?
> > 
> > 
> > It will create a separate endpoint that calls the backend and gets the cloud name from preferences, that endpoint will call from the footer or header. Are you aligned with that?
> 
> Right now we have an invisible div of class "cloudinary-data-container" in ISML files, which seems to be passed as-is to the PWA and can include both cloud_name and CNAME

That file doesn't always come, it only comes when we have enabled the content asset and video in that content asset, for our new implementation CName cannot associate with the content asset it should be independent.

**Comment by yuval-cloudinary** [comment]
I know it doesn't come always. I'd like it to come whenever a PGW or VP is enabled and include the cloud_name and CNAME. Is this doable? It doesn't look like a big change, is it?

**Comment by asad-rafter** [comment]
> I know it doesn't come always. I'd like it to come whenever a PGW or VP is enabled and include the cloud_name and CNAME. Is this doable? It doesn't look like a big change, is it?

I still try to understand how this will replace our this logic  

item.c_cloudinary.cloudName = cloudinaryConstants.CLD_CLOUDNAME;

can we jump on a call?

**Review by yuval-cloudinary — APPROVED** [review]

**Pull request merged**
