### PR TITLE
Update analytics tag

### PR DESCRIPTION
**Pull request by asad-rafter**

### CODE REVIEW

**Review by yuval-cloudinary — APPROVED** [review]

**Review by yuval-cloudinary — CHANGES_REQUESTED** [review]
The change is expected in the PWA-Kit (query param in the widgets), not the headless cartridge, please revert this

**Comment by asad-rafter** [comment]
> The change is expected in the PWA-Kit (query param in the widgets), not the headless cartridge, please revert this

**Comment by asad-rafter** [comment]
@yuval-cloudinary we have used this way previously, it's been used in CLD core cartridges. We haven't sent anything from PWA

**Comment by yuval-cloudinary** [comment]
> @yuval-cloudinary we have used this way previously, it's been used in CLD core cartridges. We haven't sent anything from PWA

@asad-rafter in the coresite cartridge there is an CLD_TRACKING_PARAM used for frontend widgets and API_TRACKING_PARAM used for backend APIs.

The PWA-Kit is a frontend and needs to have CLD_TRACKING_PARAM

**Comment by yuval-cloudinary** [comment]
The SFCC headless cartridge is not part of this change request. The tag
should be part of the PWA-Kit, it is passed to the Cloudinary widgets or
set directly in the Cloudinary URLs to media

**Pull request closed without merging**
